# Catppuccin options

# set -g status-bg default
# set -g status-style bg=default
set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_status_background "default"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_current_number_color "#{@thm_pink}"
set -g @catppuccin_window_number "#I"
set -g @catppuccin_window_current_number "#I"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
# set -g @catppuccin_window_current_text "#W (#T)"
set -g @catppuccin_window_number_position "left"
set -g @catppuccin_window_flags "icon" # none, icon, or text
set -g @catppuccin_status_directory_icon_bg "#{@thm_peach}"
set -g @catppuccin_status_uptime_icon_bg "#{@thm_green}"
set -g @catppuccin_date_time_text " %d %b, %H:%M"

run '~/.config/tmux/plugins/catppuccin-tmux/catppuccin.tmux'

set -g status-right-length 100
set -g status-left-length 100
set -g status-left "#{E:@catppuccin_status_session}  "
set -g status-right "#{E:@catppuccin_status_application}"
# set -agF status-right "#{E:@catppuccin_status_weather}"
set -ag status-right "#{E:@catppuccin_status_directory}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_date_time}"
set -agF status-right "#{E:@catppuccin_status_battery}"
# set -agF status-right "-"